const matchStatDefaultHeader = [
  {
    field: "name",
    headerName: "PLAYER",
    flex: 2,
    minWidth: 160,
    sortable: false,
  },
  {
    field: "minutes",
    headerName: "MIN",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "points",
    headerName: "PTS",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "assists",
    headerName: "AST",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "def_rebounds",
    headerName: "DREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "off_rebounds",
    headerName: "OREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "rebounds",
    headerName: "REB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "field_goal_try",
    headerName: "FGA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "field_goal_made",
    headerName: "FGM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "three_point_try",
    headerName: "3PA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "three_point_made",
    headerName: "3PM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "free_throw_try",
    headerName: "FTA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "free_throw_made",
    headerName: "FTM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "steals",
    headerName: "STL",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "blocks",
    headerName: "BLK",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  { field: "fouls", headerName: "PF", flex: 1, minWidth: 80, sortable: false },
  {
    field: "turnovers",
    headerName: "TO",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
];

export default matchStatDefaultHeader;
