const matchStatDefaultHeader = [
  {
    field: "name",
    headerName: "PLAYER",
    flex: 2.5,
    minWidth: 160,
    sortable: false,
  },
  {
    field: "minutes",
    headerName: "MIN",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "points",
    headerName: "PTS",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "assists",
    headerName: "AST",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "def_rebounds",
    headerName: "DREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "off_rebounds",
    headerName: "OREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "rebounds",
    headerName: "REB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "field_goal_try",
    headerName: "FGA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "field_goal_made",
    headerName: "FGM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "three_point_try",
    headerName: "3PA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "three_point_made",
    headerName: "3PM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "free_throw_try",
    headerName: "FTA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "free_throw_made",
    headerName: "FTM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "steals",
    headerName: "STL",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "blocks",
    headerName: "BLK",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  { field: "fouls", headerName: "PF", flex: 1, minWidth: 80, sortable: false },
  {
    field: "turnovers",
    headerName: "TO",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
];

const statPageDefaultHeader = [
  {
    field: "league_season_name",
    headerName: "SEASON",
    flex: 2,
    minWidth: 90,
  },
  { field: "team_name", headerName: "TEAM", flex: 1.5, minWidth: 100 },
  { field: "player_name", headerName: "PLAYER", flex: 2.5, minWidth: 160 },
  {
    field: "PTS",
    headerName: "PTS",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "FGM_FGA",
    headerName: "FG",
    flex: 1.5,
    minWidth: 60,
    align: "right",
    headerAlign: "right",
    sortable: false,
  },
  {
    field: "FG%",
    headerName: "FG%",
    flex: 1,
    minWidth: 50,
    align: "right",
    headerAlign: "right",
    type: "number",
  },
  {
    field: "TPM_TPA",
    headerName: "TP",
    headerAlign: "right",
    flex: 1.5,
    minWidth: 60,
    align: "right",
    sortable: false,
  },
  {
    field: "3P%",
    headerName: "TP%",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "FTM_FTA",
    headerName: "FT",
    headerAlign: "right",
    flex: 1.5,
    minWidth: 60,
    align: "right",
    sortable: false,
  },
  {
    field: "FT%",
    headerName: "FT%",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },

  {
    field: "OREB",
    headerName: "OREB",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "DREB",
    headerName: "DREB",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "REB",
    headerName: "REB",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "AST",
    headerName: "AST",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "STL",
    headerName: "STL",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "BLK",
    headerName: "BLK",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "TOV",
    headerName: "TOV",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "EFF",
    headerName: "EFF",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
  {
    field: "TSP",
    headerName: "TS%",
    headerAlign: "right",
    flex: 1,
    minWidth: 50,
    align: "right",
    type: "number",
  },
];

export { matchStatDefaultHeader, statPageDefaultHeader };
