const matchStatDefaultHeader = [
  {
    field: "name",
    headerName: "PLAYER",
    flex: 2.5,
    minWidth: 160,
    sortable: false,
  },
  {
    field: "minutes",
    headerName: "MIN",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "points",
    headerName: "PTS",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "assists",
    headerName: "AST",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "def_rebounds",
    headerName: "DREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "off_rebounds",
    headerName: "OREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "rebounds",
    headerName: "REB",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "field_goal_try",
    headerName: "FGA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "field_goal_made",
    headerName: "FGM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "three_point_try",
    headerName: "3PA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "three_point_made",
    headerName: "3PM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "free_throw_try",
    headerName: "FTA",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "free_throw_made",
    headerName: "FTM",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "steals",
    headerName: "STL",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "blocks",
    headerName: "BLK",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
  { field: "fouls", headerName: "PF", flex: 1, minWidth: 80, sortable: false },
  {
    field: "turnovers",
    headerName: "TO",
    flex: 1,
    minWidth: 80,
    sortable: false,
  },
];

const statDefaultHeader = [
  { field: "team_name", headerName: "TEAM", flex: 1.5, minWidth: 100 },
  { field: "player_name", headerName: "PLAYER", flex: 2.5, minWidth: 160 },
  { field: "PTS", headerName: "PTS", flex: 1, minWidth: 50, align: "right" },

  { field: "FGA", headerName: "FGA", flex: 1, minWidth: 50, align: "right" },
  { field: "FGM", headerName: "FGM", flex: 1, minWidth: 50, align: "right" },
  { field: "FG%", headerName: "FG%", flex: 1, minWidth: 50, align: "right" },

  { field: "3PA", headerName: "3PA", flex: 1, minWidth: 50, align: "right" },
  { field: "3PM", headerName: "3PM", flex: 1, minWidth: 50, align: "right" },
  { field: "3P%", headerName: "3P%", flex: 1, minWidth: 50, align: "right" },

  { field: "FTM", headerName: "FTM", flex: 1, minWidth: 50, align: "right" },
  { field: "FTA", headerName: "FTA", flex: 1, minWidth: 50, align: "right" },
  { field: "FT%", headerName: "FT%", flex: 1, minWidth: 50, align: "right" },

  { field: "OREB", headerName: "OREB", flex: 1, minWidth: 50, align: "right" },
  { field: "DREB", headerName: "DREB", flex: 1, minWidth: 50, align: "right" },
  { field: "REB", headerName: "REB", flex: 1, minWidth: 50, align: "right" },

  { field: "AST", headerName: "AST", flex: 1, minWidth: 50, align: "right" },
  { field: "STL", headerName: "STL", flex: 1, minWidth: 50, align: "right" },
  { field: "BLK", headerName: "BLK", flex: 1, minWidth: 50, align: "right" },
  { field: "TOV", headerName: "TOV", flex: 1, minWidth: 50, align: "right" },
  { field: "EFF", headerName: "EFF", flex: 1, minWidth: 50, align: "right" },
  { field: "TSP", headerName: "TSP", flex: 1, minWidth: 50, align: "right" },
];

export { matchStatDefaultHeader, statDefaultHeader };
