const teamRosterDefaultHeader = [
  {
    field: "player_name",
    headerName: "PLAYER",
    flex: 2.5,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "back_number",
    headerName: "#",
    flex: 1,
    minWidth: 40,
    sortable: false,
  },
  {
    field: "PTS",
    headerName: "PTS",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "FGM",
    headerName: "FGM",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "FGA",
    headerName: "FGA",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "FG%",
    headerName: "FG%",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "3PM",
    headerName: "3PM",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "3PA",
    headerName: "3PA",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "3P%",
    headerName: "3P%",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "FTM",
    headerName: "FTM",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "FTA",
    headerName: "FTA",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "FT%",
    headerName: "FT%",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "DREB",
    headerName: "DREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "OREB",
    headerName: "OREB",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "REB",
    headerName: "REB",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "AST",
    headerName: "AST",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "STL",
    headerName: "STL",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "BLK",
    headerName: "BLK",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "TOV",
    headerName: "TO",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
  {
    field: "EFF",
    headerName: "EFF",
    flex: 1,
    minWidth: 80,
    sortable: false,
    valueFormatter: ({ value }) => parseFloat(value.toFixed(3)),
  },
];

const overallStatsDefaultHeader = [
  {
    field: "name",
    headerName: "OVERALL",
    flex: 2.5,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "GP",
    headerName: "GP",
    flex: 1,
    minWidth: 40,
    sortable: false,
  },
];
const locationStatsDefaultHeader = [
  {
    field: "name",
    headerName: "LOCATION",
    flex: 2.5,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "back_number",
    headerName: "#",
    flex: 1,
    minWidth: 40,
    sortable: false,
  },
];
const winlossStatsDefaultHeader = [
  {
    field: "name",
    headerName: "WINS/LOSSES",
    flex: 2.5,
    minWidth: 80,
    sortable: false,
  },
  {
    field: "back_number",
    headerName: "#",
    flex: 1,
    minWidth: 40,
    sortable: false,
  },
];

export {
  teamRosterDefaultHeader,
  overallStatsDefaultHeader,
  locationStatsDefaultHeader,
  winlossStatsDefaultHeader,
};
